CEDS-3081 Splitting 'notifications' Mongo collection
hmrc/customs-declare-exports pull request #261
Opened 2021-04-13 10:34 UTC by MaciejRewera

2021-04-21 13:04 UTC, MaciejRewera commented
Test this please

2021-04-23 07:45 UTC, glidester requested changes
A very complex task well done :+1:  All looks good functionally, only thing outstanding is to improve the readability/discoverability of the whole notification ingestion process. I think a descriptive java doc comments on the `SplitNotificationsCollection` class would really help, and/or a description in the project README of the process will aid those who come after us :grin:

2021-04-26 15:41 UTC, glidester submitted a review, later dismissed
LGTM :+1:

2021-04-26 15:46 UTC, glidester approved these changes

2021-04-26 16:09 UTC, merged